### PR TITLE
Feature/dispositions

### PR DESCRIPTION
**Pull request by egreer**
Adds dispositions to the efax

### CODE REVIEW

**Review by wkirby — APPROVED** [review]

**Comment by wkirby** [comment]
This looks good. Are we going to make a PR upstream?

**Review by ncallaway — APPROVED** [review]

**Comment by ncallaway** [comment]
Agreed that we might as well create the upstream PR.

**Comment by wkirby** [comment]
@egreer What happened with this PR?

**Comment by egreer** [comment]
@wkirby I never merged it or tried to push upstream. Merging now

**Pull request merged**
